### ISSUE TITLE
Switching back to handyhat branch

### ISSUE THREAD

**Issue by jk1993** [ColinRobbins/ha-hildebrandglow-dcc#26]
Hi,

I know this is no longer maintained and I should switch back to the original repo this is forked from.

If I do this, will I lose the existing data I have on home assistant? Or is it as simple as uninstalling this one and installing the other and the sensors match up automatically?

Just want to make sure before I do it so I don't lose any data.

Thanks

Jack

**Comment by ColinRobbins** [comment]
There should be no loss of data from uninstalling, and revering to the @handyhat version.
