### ISSUE TITLE
manually set tariff data

### ISSUE THREAD

**Issue by That-Dude** [ColinRobbins/ha-hildebrandglow-dcc#28]
Hi

First of all thanks for this integration, it's amazing!

I have a minor issue, Bright is synced to my meter and grabs all of the usage data except for the tariffs (standing and unit cost), they are displaying as 'Unavailable' in Home Assistant.

My tariffs are fixed, so is there a way that I can set them manually?

**Comment by ColinRobbins** [comment]
You can’t set the values from the HA sensor.
But you can create a [helper](https://www.home-assistant.io/integrations/input_number/) and use that.

**Comment by That-Dude** [comment]
Apologies Colin, I think that I described the problem poorly. It's these 'unavailable' fields that I wanted to change.

<img width="396" alt="Screenshot 2022-06-02 at 16 46 07" src="https://user-images.githubusercontent.com/6509533/171669154-fefbafb3-e6bc-4528-8dd1-35a58608bc7f.png">

I hoped there was a way to set the state to fixed values somehow. Either through HA or via a change to your Python code so that it reports constant values to those sensors.

**Comment by ColinRobbins** [comment]
Overriding them would be hard.
Why not disable them in the HA, and use a number helper instead?

Also, you should nudge you provider to make the data available - it kind of the whole point of a smart meter that you can see how much it costs!  They have an obligation to fix it!

**Comment by That-Dude** [comment]
You're right, I'll email Shell Energy and see if they can fix it. They do have the price data exposed in the own monitoring app, they just don't seem to be providing it to Bright.

I was hoping to adapt your sensor as it's all pretty and organised in the HA interface.

I've figured out a hacky solution by setting the entities with an automation so you can close this off.

Thanks so much for your help.
